### ISSUE TITLE
Docker login doesn't support spaces

### ISSUE THREAD

**Issue by AssafKatz3** [prometheus/circleci#12]
Hi,
[publish_images](../blob/master/src/commands/publish_images.yml#L46) command contains:
`- run: docker login -u $<< parameters.login_variable >> -p $<< parameters.password_variable >> << parameters.registry >>`
But this code doesn't work if login_variable or password_variable contains spaces. As far as I know, there is no repository that allow space in user name but [JSON key file of JCR](https://cloud.google.com/container-registry/docs/advanced-authentication#json-key) uses full file for password. Therefore I suggest to replace the line above to:
`- run: echo $<< parameters.password_variable >> | docker login -u $<< parameters.login_variable >> --password-stdin  << parameters.registry >>`
I hope to open a pull request about it soon.
Thanks

**Comment by simonpasquier** [comment]
closed by #13
